{% set data = load_setup_py_data() %}

package:
  name: pytmc
  version : {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5

test:
  imports:
    - pytmc
  requires:
    - codecov
    - coverage
    - pytest
    - pytest-qt
    - qtpy
    - pyqt

about:
  home: https://github.com/slaclab/pytmc
  doc_url: https://slaclab.github.io/pytmc/
  license: SLAC Open
  license_family: Other
  license_file: LICENSE
  summary: 'Generate EPICS IOCs and records from Beckhoff TwinCAT projects'

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka 
    - zllentz
    - n-wbrown
